name: sync rajikak => consulting
run-name: ${{ github.actor }} is updating repos using GitHub Actions üöÄ
on: [push]
jobs:
  sync-rajikak-to-baranasoftware:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: adrianjost/files-sync-action@v2.0.4
        with:
          GIT_EMAIL: nrajikak@gmail.com
          FILE_PATTERNS: |
            ^LICENSE$
            ^.github/workflows/sync-.*
            README.md
            .gitignore
            src/
            Cargo.lock
            Cargo.toml
          GITHUB_TOKEN: '${{ secrets.BARANASOFTWARE_TOKEN }}'
          TARGET_REPOS: |
            baranasoftware/tool-chain:main
      - uses: adrianjost/files-sync-action@v2.0.4
        with:
          GIT_EMAIL: nkconsultinglab@gmail.com
          FILE_PATTERNS: |
            ^LICENSE$
            ^.github/workflows/sync-.*
            README.md
            .gitignore
            src/
            Cargo.lock
            Cargo.toml
          GITHUB_TOKEN: '${{ secrets.NKCONSULTING_TOKEN }}'
          TARGET_REPOS: |
            nkconsultinglab/tool-chain:main
      - run: echo "üçè This job's status is ${{ job.status }}."
